# Generated by Django 4.0.2 on 2022-03-18 09:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_project_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='address',
            new_name='city',
        ),
        migrations.AddField(
            model_name='university',
            name='specialization',
            field=models.CharField(default='None', max_length=120),
        ),
        migrations.AddField(
            model_name='university',
            name='website',
            field=models.CharField(default='none', max_length=250),
        ),
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
