# Generated by Django 4.0.2 on 2022-03-18 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_address_university_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='email',
            field=models.EmailField(default='default@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
