# Generated by Django 4.0.2 on 2022-03-18 10:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_university_email_alter_project_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='brief',
        ),
        migrations.RemoveField(
            model_name='university',
            name='specialization',
        ),
        migrations.AddField(
            model_name='member',
            name='designation',
            field=models.CharField(default='Viewer', max_length=100),
        ),
        migrations.AddField(
            model_name='university',
            name='brief',
            field=models.TextField(default=2, max_length=3000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
