# Generated by Django 4.0.2 on 2022-03-20 05:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_image_image_alter_project_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='university',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
